# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 498)
        MainWindow.setStyleSheet("background-color: black\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Slot1 = QtWidgets.QCheckBox(self.centralwidget)
        self.Slot1.setGeometry(QtCore.QRect(70, 20, 81, 31))
        self.Slot1.setStyleSheet("background-color: yellow")
        self.Slot1.setObjectName("Slot1")
        self.Slot2 = QtWidgets.QCheckBox(self.centralwidget)
        self.Slot2.setGeometry(QtCore.QRect(175, 20, 81, 31))
        self.Slot2.setStyleSheet("background-color: yellow\n"
"")
        self.Slot2.setObjectName("Slot2")
        self.Slot3 = QtWidgets.QCheckBox(self.centralwidget)
        self.Slot3.setGeometry(QtCore.QRect(275, 20, 81, 31))
        self.Slot3.setStyleSheet("background-color: yellow")
        self.Slot3.setObjectName("Slot3")
        self.Slot4 = QtWidgets.QCheckBox(self.centralwidget)
        self.Slot4.setGeometry(QtCore.QRect(370, 20, 81, 31))
        self.Slot4.setStyleSheet("background-color: yellow")
        self.Slot4.setObjectName("Slot4")
        self.Slot5 = QtWidgets.QCheckBox(self.centralwidget)
        self.Slot5.setGeometry(QtCore.QRect(470, 20, 81, 31))
        self.Slot5.setStyleSheet("background-color: yellow")
        self.Slot5.setObjectName("Slot5")
        self.SendMsg = QtWidgets.QPushButton(self.centralwidget)
        self.SendMsg.setGeometry(QtCore.QRect(670, 190, 100, 36))
        self.SendMsg.setStyleSheet("background-color: white\n"
"")
        self.SendMsg.setObjectName("SendMsg")
        self.AlertOn = QtWidgets.QPushButton(self.centralwidget)
        self.AlertOn.setGeometry(QtCore.QRect(60, 170, 101, 101))
        self.AlertOn.setStyleSheet("QPushButton {\n"
"    border-radius: 50%;\n"
"    background-color: green\n"
"    \n"
"}\n"
"")
        self.AlertOn.setObjectName("AlertOn")
        self.AlertOff = QtWidgets.QPushButton(self.centralwidget)
        self.AlertOff.setGeometry(QtCore.QRect(60, 280, 101, 101))
        self.AlertOff.setStyleSheet("QPushButton {\n"
"    border-radius: 50%;\n"
"    background-color: red\n"
"}\n"
"")
        self.AlertOff.setObjectName("AlertOff")
        self.MsgBox = QtWidgets.QTextEdit(self.centralwidget)
        self.MsgBox.setGeometry(QtCore.QRect(250, 110, 381, 251))
        self.MsgBox.setStyleSheet("background-color: white\n"
"")
        self.MsgBox.setObjectName("MsgBox")
        self.SensorDisplay = QtWidgets.QLabel(self.centralwidget)
        self.SensorDisplay.setGeometry(QtCore.QRect(682, 29, 171, 51))
        self.SensorDisplay.setStyleSheet("background-color: white\n"
"")
        self.SensorDisplay.setObjectName("SensorDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Slot1.setText(_translate("MainWindow", "Slot 1"))
        self.Slot2.setText(_translate("MainWindow", "Slot 2"))
        self.Slot3.setText(_translate("MainWindow", "Slot 3"))
        self.Slot4.setText(_translate("MainWindow", "Slot 4"))
        self.Slot5.setText(_translate("MainWindow", "Slot 5"))
        self.SendMsg.setText(_translate("MainWindow", "Send"))
        self.AlertOn.setText(_translate("MainWindow", "On"))
        self.AlertOff.setText(_translate("MainWindow", "Off"))
        self.SensorDisplay.setText(_translate("MainWindow", "TextLabel"))
